#Load the required packages.
library(tidyverse) #data manipulation
library(ggplot2) #data visualization
library(lattice)

#Set working directory where dataset is located.
setwd("C:/Users/grandhi vaishnavi/OneDrive/Desktop/3-2/project") #change this location to where your files are located.

#Import the dataset.
data <- read.csv("train.csv")

#create a copy of the dataset.
data1 <- data

#remove ID column.
data1$ID <- NULL

#rename variables.
names(data1) <- c("warehouseblock", "modeofshipment", "customercarecalls", "customerrating", "costoftheproduct", "priorpurchase", "productimportance", "gender", "discountoffered", "weightingrams", "reachedontime")

#check for any missing values column-wise.
colSums(is.na(data)) #No missing values in the dataset.

#structure and summary of the dataset
str(data1)
summary(data1)

#check the proportion of target variable - "reachedontime"
table(data1$reachedontime) #4436 orders were delivered on time. 6563 orders were not delivered on time. 


#convert target variable to factor.
data1$reachedontime <- as.factor(data1$reachedontime)

#check for unique levels in the following variables.
unique(data1$priorpurchase) 
unique(data1$customercarecalls)
unique(data1$customerrating)

#convert the above three variables to factor.
data1$priorpurchase <- as.factor(data1$priorpurchase)
data1$customercarecalls <- as.factor(data1$customercarecalls)
data1$customerrating <- as.factor(data1$customerrating)

#structure and summary of the dataset.
str(data1)
summary(data1)

#Delivery rate
prop.table(table(data1$reachedontime))
#On-time delivery rate is 40.33 %
#Delayed delivery rate is 59.66 %

options(scipen = 999) #convert scientific notation to readable numbers

#Average order value = Total Revenue / Total number of orders
sum(data1$costoftheproduct) #2311955 (approx. 2.3 Million US dollars)
averageordervalue <-2311955/10999
averageordervalue #the average amount of money each customer ends up spending per transaction is 210.19 US Dollars
#To improve this value, the e-commerce company should recommend relevant products, set order minimums for discount/free shipping, bundle products.

table(data1$priorpurchase)# Maximum customers in the dataset have made prior purchase of three items
#Minimum number of customers in the dataset have made prior purchases of 8 items

#Revenue generated by customers who have made 3 prior purchases
revenue1 <- data1 %>% filter(priorpurchase == "3") %>% summarise(revenue1 = sum(costoftheproduct))
revenue1 #791585 US Dollars (approx. 791.5 thousand US Dollars)

#Revenue generated by customers who have made less than 6 prior purchases
revenue2 <- data1 %>% filter(priorpurchase == "8") %>% summarise(revenue2 = sum(costoftheproduct))
revenue2 #25590 US Dollars (approx. 25.5 thousand US Dollars)

# CONTINGENCY TABLES
#Warehouse and reached on time.
xtabs(~ warehouseblock + reachedontime, data = data1)
#most activity from the F block of the warehouse

#Mode of Shipment and reached on time.
xtabs(~ modeofshipment + reachedontime, data = data1)
#A large share of deliveries are done with ships

#Customer care calls and reached on time.
xtabs(~ customercarecalls + reachedontime, data = data1)
#maximum customers in the dataset have made 4 calls to customer care.

#Customer rating and reached on time.
xtabs(~ customerrating + reachedontime, data = data1)
#Maximum customers were rated 3, followed by those rated 1.
#882 customers  who have been rated 3, received their orders on time.
#922 custumers who have been rated 1, received their orders on time.
#854 customers who were rated 5, received orders on time, while 1317 customers with the same rating didnt recieve orders on time.

#Prior purchase and reached on time.
xtabs(~ priorpurchase + reachedontime, data = data1)
#majority of the customers have made 3 prior purchases.

#product importance
xtabs(~ productimportance + reachedontime, data = data1)
#most of the customers have purchased products with low importance, It evidently shows the largest delayed time.
#however data also shows that  most customers who bought low priority products had also recieved the products on time.

#discount offered
xtabs( ~ discountoffered + reachedontime, data = data1)
#customers who bought product with less than 11% discount offer/coupons didnt recieve products on time
#while customers who purchased products having more than 11% discount didnt have  delay in recieving the shipment.
max(data1$discountoffered) # 65% discount
min(data1$discountoffered) # 1% discount
#Categorizing the discounts 
#describe(data1$discountoffered)#65 unique discount categories
data1$discount_group[data1$discountoffered <=15 & data1$discountoffered>= 1] <- "1" #lowest
data1$discount_group[data1$discountoffered <= 30 & data1$discountoffered >15] <- "2"
data1$discount_group[data1$discountoffered <= 45 & data1$discountoffered >30] <- "3"
data1$discount_group[data1$discountoffered <= 50 & data1$discountoffered >45] <- "4"
data1$discount_group[data1$discountoffered <= 65 & data1$discountoffered >50] <- "5" #highest
data1$discount_group <- as.factor(data1$discount_group)
barchart(data1$discount_group, main = "Discount Categories", sub = "1 indicates Lowest discount category and 5 indicates highest", xlab = "No of customers")

#weight in grams
xtabs(~ weightingrams + reachedontime, data = data1)
#There is no special observation
which.min(data1$weightingrams) #row number 2664 shows product shipped has min weight (1001 grams)
which.max(data1$weightingrams) #row number 200 shows product shipped has max weight (7846 grams)


#data visualization
#Prior Purchase and reached on-time.
ggplot(data1, aes(priorpurchase)) + geom_bar(aes(fill = reachedontime), position = "dodge") + scale_fill_manual(values=c("green","red")) +  
  labs(title = "Prior purchase and reached on-time", x = "Number of Prior purchases", caption = "Maximum no. of customers had made prior purchases of three products") 

#Customer rating and reached on-time.
ggplot(data1, aes(customerrating)) +geom_bar(aes(fill = reachedontime), position = "dodge") + scale_fill_manual(values=c("green","red")) +  
  labs(title = "Customer rating and reached on-time", x = "Customer rating", caption = "Majority of customers were rated 3, followed by customers who were rated 1 ") 

#Product importance and reached on-time.
ggplot(data1, aes(productimportance)) +geom_bar(aes(fill = reachedontime), position = "dodge") + scale_fill_manual(values=c("green","red")) +  
  labs(title = "Product importance and reached on-time", x = "Product importance", caption = "Majority of products were of low importance ") 

#Gender and reached on-time.
ggplot(data1, aes(gender)) +geom_bar(aes(fill = reachedontime), position = "dodge") + scale_fill_manual(values=c("green","red")) +  
  labs(title = "Gender and reached on-time", x = "Gender", caption = "Both genders show equal distribution") 

#Warehouse block and reached on-time.
ggplot(data1, aes(warehouseblock)) +geom_bar(aes(fill = reachedontime), position = "dodge") + scale_fill_manual(values=c("green","red")) +  
  labs(title = "Warehouse block and reached on-time", x = "Warehouse blocks", caption = "Most activity from the F block of the warehouse") 

#Mode of shipment and reached on-time.
ggplot(data1, aes(modeofshipment)) +geom_bar(aes(fill = reachedontime), position = "dodge") + scale_fill_manual(values=c("green","red")) +  
  labs(title = "Mode of shipment and reached on-time", x = "Mode of shipment", caption = "A large share of deliveries were done with ships") 

#Customer care calls and reached on-time.
ggplot(data1, aes(customercarecalls)) + geom_bar(aes(fill = reachedontime), position = "dodge") + scale_fill_manual(values=c("green","red")) +  
  labs(title = "Customer care calls and reached on-time", x = "Number of Customer care calls", caption = "Maximum no. of customers in the dataset have made 4 calls to customer care") 

#Histogram for Cost of the product
ggplot(data1, aes(costoftheproduct)) + geom_histogram(breaks=seq(90, 310, by=10), col="red", fill="green", alpha = .2) + 
  labs(title="Histogram for Cost of the product (in US dollars)", x="Cost of the product($)", caption = "The purchase with the highest value is $ 310") 

#Histogram for Weight (in grams)
ggplot(data1, aes(weightingrams)) + geom_histogram(breaks=seq(1000, 8000, by=100), col="red", fill="green", alpha = .2) + 
  labs(title="Histogram for Weight (in grams)", x="Weight(in grams)", caption = "Minimum weight of an order is 1001 grams. Maximum weight of an order is 7846 grams") 

#Histogram for Discount offered
ggplot(data1, aes(discountoffered)) + geom_histogram(breaks=seq(0, 70, by=5), col="red", fill="green", alpha = .2) + 
  labs(title="Histogram for Discount offered", x="Percentage of Discount offered", caption = "Maximum discount offered  by the company is 65 %, and minimum discount offered is 1 %.") 







                            #Logistic Regression for Customer Analysis

#Load the required packages.
install.packages("car")
install.packages("caret")
library(caret) #confusion matrix
library(car) #to check for multicollinearity

#Set working directory where dataset is located.
setwd("C:/Users/grandhi vaishnavi/OneDrive/Desktop/3-2/project")

#Import the dataset.
data <- read.csv("train.csv")

#create a copy of the dataset.
data1 <- data

#remove ID column.
data1$ID <- NULL

#rename variables.
names(data1) <- c("warehouseblock", "modeofshipment", "customercarecalls", "customerrating", "costoftheproduct", "priorpurchase", "productimportance", "gender", "discountoffered", "weightingrams", "reachedontime")

#check for any missing values column-wise.
colSums(is.na(data)) #No missing values in the dataset.

#structure and summary of the dataset
str(data1)
summary(data1)

#check the proportion of target variable - "reachedontime"
table(data1$reachedontime) #4436 orders were delivered on time. 6563 orders were not delivered on time. 
#There is class imbalance.

#convert target variable to factor.
data1$reachedontime <- as.factor(data1$reachedontime)

#check for unique levels in the following variables.
unique(data1$priorpurchase) 
unique(data1$customercarecalls)
unique(data1$customerrating)

#convert the above three variables to factor.
data1$priorpurchase <- as.factor(data1$priorpurchase)
data1$customercarecalls <- as.factor(data1$customercarecalls)
data1$customerrating <- as.factor(data1$customerrating)

#structure and summary of the dataset.
str(data1)
summary(data1)


#split dataset into train and test data. The latter is for validation purpose.
set.seed(1234)
trainsample1 <- sample(1:nrow(data1), 0.7 * nrow(data1))
train1 <- data1[trainsample1,]
test1 <- data1[-trainsample1,]

#proportion of target variable in train and test data
table(train1$reachedontime)
#Baseline model
model1 <- glm(reachedontime ~ ., data = train1, family = binomial(link = "logit"))
summary(model1)
#AIC : Akaike Information Criterion
# FORMULA : AIC=−2×Log-Likelihood+2×Number of Parameters
#AIC : 8387.8

#Check for multicollinearity
vif(model1) #all variables are independent

#predict for test data using baseline model 
pred <- predict(model1, newdata = test1, type = 'response')

#Confusion matrix
confusionMatrix(data= as.factor(as.numeric(pred >= 0.5)), reference = test1$reachedontime, positive = "0")
#Accuracy for the baseline model is 64.48 %


#stepwise model from baseline model 
stepmodel1 <-  step(model1 , direction = "both")

formula(stepmodel1)
#reachedontime ~ customercarecalls + costoftheproduct + 
#priorpurchase + productimportance + discountoffered + weightingrams

summary(stepmodel1)
#AIC : 8370.7

#predict for stepwise model 1
predstep1 <-  predict(stepmodel1, newdata = test1)

#confusion matrix for stepwise model 1
confusionMatrix(data= as.factor(as.numeric(predstep1 >= 0.5)), reference = test1$reachedontime, positive = "0")
#Accuracy for stepwise model 1 is 66.55%

#CONCLUSION
#Accuracy comparison
#Baseline model (Model 1)                                           : 64.48%
#Stepwise model from Model 1                                        : 66.55%


#I will chose Stepwise model because it has fairly better accuracy than the base model and includes only significant variables
#Important variables are customercarecalls, costoftheproduct, priorpurchase.
#productimportance, discountoffered, weightingrams

#Now to predict if shipments reached on time or not using stepwise model on new data
datatest <- read.csv("test.csv")
datatest$ID <- NULL
colSums(is.na(datatest))
names(datatest) <- c("warehouseblock", "modeofshipment", "customercarecalls", "customerrating", "costoftheproduct", "priorpurchase", "productimportance", "gender", "discountoffered", "weightingrams", "reachedontime")

summary(datatest)
#convert customerrating into factor

datatest$priorpurchase <- as.factor(datatest$priorpurchase)
datatest$customerrating <- as.factor(datatest$customerrating)
datatest$customercarecalls <- as.factor(datatest$customercarecalls)

pred_datatest <- predict(stepmodel1, newdata = datatest)
datatest$reachedontime <- NULL
datatest$reachedontime <- round(exp(pred_datatest)/(1 + exp(pred_datatest)), digits = 0)

summary(stepmodel1)
#coeffients  are in a form called logits
#if coefficients (logits) are positive, the effect on timely delivery is positive
#when negative, higher the value for signifcant variables, lower the probability of timely delivery




                          #clustering hierarchical
#HIERARCHICAL CLUSTERING

#Load the required packages.
library(tidyverse) #for data manipulation


#Set working directory where dataset is located.
setwd("C:/Users/grandhi vaishnavi/OneDrive/Desktop/3-2/project")

#Import the dataset.
data <- read.csv("train.csv")

#create a copy of the dataset.
data1 <- data

#remove ID column.
data1$ID <- NULL

#rename variables.
names(data1) <- c("warehouseblock", "modeofshipment", "customercarecalls", "customerrating", "costoftheproduct", "priorpurchase", "productimportance", "gender", "discountoffered", "weightingrams", "reachedontime")

#check for any missing values column-wise.
colSums(is.na(data)) #No missing values in the dataset.

#structure and summary of the dataset
str(data1)
summary(data1)

#check the proportion of target variable - "reachedontime"
table(data1$reachedontime) #4436 orders were delivered on time. 6563 orders were not delivered on time. 

#convert target variable to factor.
data1$reachedontime <- as.factor(data1$reachedontime)

#structure and summary of the dataset.
str(data1)
summary(data1)

#Ony delayed customer data for cluster segmentation
clustdata <- data1 %>% filter(reachedontime == "1") #6563 observations

#Only need variables that are related to/ impact the customer.
clustdata2 <- clustdata[,c(3,4,5,6,8,9)]
clustdata2$gender <- ifelse(clustdata2$gender == "F", 0, 1) #dummy variable

#scale the data
clustdata2.scale <- scale(clustdata2)

#Hierarchial clustering
d <-  dist(clustdata2.scale, method = "euclidean")

H.fit <- hclust(d, method = "ward")

#display dendrogram
plot(H.fit, labels=FALSE, hang=-1) #it is observe that the tree can be cut into three clusters

#draw borders on the dendrogram indicating the cluster groups
rect.hclust(H.fit, k = 3,  border = "red")

#cut the tree into 3 clusters
clustergroups <- cutree(H.fit, k = 3) 
table(clustergroups) #cluster size

#assign clustergroups to the dataset clustdata2
clustdata2$cluster  <- clustergroups

#understand customer profiles from the clusters
customer_profiles <-  clustdata2 %>% group_by(cluster) %>% summarise_all(funs(mean))

cluster_count <- clustdata2 %>% group_by(cluster) %>% summarise(counts = n())

customer_profiles <- mutate(customer_profiles, counts = cluster_count$counts)
customer_profiles

#lets explore each of the three clusters
#CLUSTER 1
cluster1 <- subset(clustdata2, cluster == 1)
cluster1
prop.table(table(cluster1$customercarecalls)) #Most customers made 3 calls to the customer care
prop.table(table(cluster1$customerrating)) #Most of the customers were rated 2
median(cluster1$costoftheproduct) #Median cost of the product is 198 US dollars
prop.table(table(cluster1$priorpurchase)) #Most of the customers made 3 prior purchases
prop.table(table(cluster1$gender))#Majority of customers in cluster 1 are male.
median(cluster1$discountoffered)#46 %

#CLUSTER 2
cluster2 <- subset(clustdata2, cluster == 2)
cluster2
prop.table(table(cluster2$customercarecalls)) #Most customers made 5 calls to the customer care
prop.table(table(cluster2$customerrating)) #Most of the customers were rated 5
median(cluster2$costoftheproduct) #Median cost of the product is 244 US dollars
prop.table(table(cluster2$priorpurchase)) #Most of the customers made 4 prior purchases
prop.table(table(cluster2$gender))#Majority of customers in cluster 2 are female.
median(cluster2$discountoffered)#7 %

#CLUSTER 3
cluster3 <- subset(clustdata2, cluster == 3)
cluster3
prop.table(table(cluster3$customercarecalls)) #Most customers made 3 calls to the customer care
prop.table(table(cluster3$customerrating)) #Most of the customers were rated 3
median(cluster3$costoftheproduct) #Average cost of the product is 197 US dollars
prop.table(table(cluster3$priorpurchase)) #Most of the customers made 3 prior purchases
prop.table(table(cluster3$gender))#Majority of customers in cluster 3 are male.
median(cluster3$discountoffered)#7%